# Generated by Django 6.1.2 on 2026-10-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('bts', 'BTS equipment'), ('antenna', 'Antenna'), ('battery', 'Battery'), ('generator', 'Generator'), ('rectifier', 'Rectifier'), ('router', 'Router'), ('switch', 'Switch'), ('other', 'Other')], default='other', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('faulty', 'Faulty'), ('under_maintenance', 'Under maintenance')], default='working', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='sites_app.site')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['site__site_code', 'category', 'name'],
            },
        ),
    ]
