# Generated by Django 6.1.2 on 2026-10-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine inspection'), ('preventive', 'Preventive maintenance'), ('corrective', 'Corrective maintenance'), ('repair', 'Equipment repair'), ('battery', 'Battery maintenance'), ('power', 'Power maintenance')], default='routine', max_length=20)),
                ('description', models.TextField(help_text='Work performed')),
                ('next_due_date', models.DateField(blank=True, help_text='Optional: when the next visit is due', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='sites_app.site')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-maintenance_date', '-created_at'],
            },
        ),
    ]
