# Generated by Django 6.1.2 on 2026-10-09 10:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('directions_note', models.TextField(blank=True, help_text='How to reach the site, landmarks, who holds the key, etc.')),
                ('has_2g', models.BooleanField(default=False)),
                ('has_3g', models.BooleanField(default=False)),
                ('has_4g', models.BooleanField(default=False)),
                ('has_5g', models.BooleanField(default=False)),
                ('power_source', models.CharField(choices=[('grid', 'Grid electricity'), ('solar', 'Solar'), ('generator', 'Generator'), ('hybrid', 'Hybrid (more than one)')], default='grid', max_length=20)),
                ('battery_type', models.CharField(blank=True, max_length=60)),
                ('battery_count', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_capacity_ah', models.PositiveIntegerField(blank=True, help_text='Capacity per battery, in Ah', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site_code'],
            },
        ),
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_photos/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('access_road', 'Access road / approach'), ('gate', 'Entrance / gate'), ('shelter', 'Shelter / equipment room'), ('tower', 'Tower'), ('surroundings', 'Surroundings / landmark')], default='surroundings', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sites_app.site')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
