# Generated by Django 6.1.2 on 2026-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitephoto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='site_photos/thumbs/%Y/%m/'),
        ),
    ]
